OBJ_CLASSES = (
    "adult",
    "baby",
    "bag",
    "ball",
    "ballon",
    "basket",
    "bat",
    "bed",
    "bench",
    "beverage",
    "bike",
    "bird",
    "blanket",
    "board",
    "book",
    "bottle",
    "bowl",
    "box",
    "bread",
    "brush",
    "bucket",
    "cabinet",
    "cake",
    "camera",
    "can",
    "candle",
    "car",
    "card",
    "carpet",
    "cart",
    "cat",
    "cellphone",
    "chair",
    "child",
    "chopstick",
    "cloth",
    "computer",
    "condiment",
    "cookie",
    "countertop",
    "cover",
    "cup",
    "curtain",
    "dog",
    "door",
    "drawer",
    "dustbin",
    "egg",
    "fan",
    "faucet",
    "fence",
    "flower",
    "fork",
    "fridge",
    "fruit",
    "gift",
    "glass",
    "glasses",
    "glove",
    "grain",
    "guitar",
    "hat",
    "helmet",
    "horse",
    "iron",
    "knife",
    "light",
    "lighter",
    "mat",
    "meat",
    "microphone",
    "microwave",
    "mop",
    "net",
    "noodle",
    "others",
    "oven",
    "pan",
    "paper",
    "piano",
    "pillow",
    "pizza",
    "plant",
    "plate",
    "pot",
    "powder",
    "rack",
    "racket",
    "rag",
    "ring",
    "scissor",
    "shelf",
    "shoe",
    "simmering",
    "sink",
    "slide",
    "sofa",
    "spatula",
    "sponge",
    "spoon",
    "spray",
    "stairs",
    "stand",
    "stove",
    "switch",
    "table",
    "teapot",
    "towel",
    "toy",
    "tray",
    "tv",
    "vaccum",
    "vegetable",
    "washer",
    "window",
    "ceiling",
    "floor",
    "grass",
    "ground",
    "rock",
    "sand",
    "sky",
    "snow",
    "tree",
    "wall",
    "water")

PREDICATE_CLASSES = (    
    "beside",
    "biting",
    "blowing",
    "brushing",
    "caressing",
    "carrying",
    "catching",
    "chasing",
    "cleaning",
    "closing",
    "cooking",
    "cutting",
    "drinking from",
    "eating",
    "entering",
    "feeding",
    "grabbing",
    "guiding",
    "hanging from",
    "hitting",
    "holding",
    "hugging",
    "in",
    "in front of",
    "jumping from",
    "jumping over",
    "kicking",
    "kissing",
    "licking",
    "lighting",
    "looking at",
    "lying on",
    "next to",
    "on",
    "opening",
    "over",
    "picking",
    "playing",
    "playing with",
    "pointing to",
    "pulling",
    "pushing",
    "riding",
    "running on",
    "shaking hand with",
    "sitting on",
    "standing on",
    "stepping on",
    "stirring",
    "swinging",
    "talking to",
    "throwing",
    "touching",
    "toward",
    "walking on",
    "watering",
    "wearing")